/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.OperacaoMatematica;
import br.com.controle.Soma;
import br.com.controle.Subtracao;
import br.com.controle.Multiplicacao;
import br.com.controle.Divisao;
import br.com.controle.Media;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo.santos2023
 */
public class Tela extends javax.swing.JFrame {

    public static double calcule(OperacaoMatematica op, double valor1, double valor2) {
        return op.calcular(valor1, valor2);
    }

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTValor1 = new javax.swing.JTextField();
        jTValor2 = new javax.swing.JTextField();
        jLResultado = new javax.swing.JLabel();
        jBSoma = new javax.swing.JButton();
        jBSubtracao = new javax.swing.JButton();
        jBMultiplicacao = new javax.swing.JButton();
        jBDivisao = new javax.swing.JButton();
        jBMedia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite a nota 1: ");

        jLabel2.setText("Digite a nota 2: ");

        jTValor1.setColumns(4);
        jTValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTValor1ActionPerformed(evt);
            }
        });

        jTValor2.setColumns(4);
        jTValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTValor2ActionPerformed(evt);
            }
        });

        jLResultado.setText("0.0");

        jBSoma.setText("+");
        jBSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaActionPerformed(evt);
            }
        });

        jBSubtracao.setText("-");
        jBSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubtracaoActionPerformed(evt);
            }
        });

        jBMultiplicacao.setText("*");
        jBMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicacaoActionPerformed(evt);
            }
        });

        jBDivisao.setText("/");
        jBDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivisaoActionPerformed(evt);
            }
        });

        jBMedia.setText("Media");
        jBMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSoma)
                        .addGap(18, 18, 18)
                        .addComponent(jBSubtracao)
                        .addGap(18, 18, 18)
                        .addComponent(jBMultiplicacao)
                        .addGap(18, 18, 18)
                        .addComponent(jBDivisao)
                        .addGap(18, 18, 18)
                        .addComponent(jBMedia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSoma)
                    .addComponent(jBSubtracao)
                    .addComponent(jBMultiplicacao)
                    .addComponent(jBDivisao)
                    .addComponent(jBMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLResultado)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTValor1ActionPerformed

    private void jTValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTValor2ActionPerformed

    private void jBSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaActionPerformed
        // TODO add your handling code here:
        if (jTValor1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor1.requestFocus();
        } else if (jTValor2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTValor1.getText());
            double pvalor2 = Double.valueOf(jTValor2.getText());
            jLResultado.setText("Soma " + calcule(new Soma(), pvalor1, pvalor2));
            jTValor1.setText("");
            jTValor2.setText("");
            jTValor1.requestFocus();
        }
    }//GEN-LAST:event_jBSomaActionPerformed

    private void jBSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubtracaoActionPerformed
        // TODO add your handling code here:
        if (jTValor1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor1.requestFocus();
        } else if (jTValor2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTValor1.getText());
            double pvalor2 = Double.valueOf(jTValor2.getText());
            jLResultado.setText("Subtracao " + calcule(new Subtracao(), pvalor1, pvalor2));
            jTValor1.setText("");
            jTValor2.setText("");
            jTValor1.requestFocus();
        }
    }//GEN-LAST:event_jBSubtracaoActionPerformed

    private void jBDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDivisaoActionPerformed
        // TODO add your handling code here:
        if (jTValor1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor1.requestFocus();
        } else if (jTValor2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor2.requestFocus();
        } else if (jTValor2.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "divisão por zero não permitida");
            jTValor2.setText("");
            jTValor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTValor1.getText());
            double pvalor2 = Double.valueOf(jTValor2.getText());
            jLResultado.setText("Divisão " + calcule(new Divisao(), pvalor1, pvalor2));
            jTValor1.setText("");
            jTValor2.setText("");
            jTValor1.requestFocus();
        }
    }//GEN-LAST:event_jBDivisaoActionPerformed

    private void jBMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMediaActionPerformed
        // TODO add your handling code here:
        if (jTValor1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor1.requestFocus();
        } else if (jTValor2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTValor1.getText());
            double pvalor2 = Double.valueOf(jTValor2.getText());
            jLResultado.setText("Média " + calcule(new Media(), pvalor1, pvalor2));
            jTValor1.setText("");
            jTValor2.setText("");
            jTValor1.requestFocus();
        }
    }//GEN-LAST:event_jBMediaActionPerformed

    private void jBMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicacaoActionPerformed
        // TODO add your handling code here:
        if (jTValor1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor1.requestFocus();
        } else if (jTValor2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "campo obrigatorio");
            jTValor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTValor1.getText());
            double pvalor2 = Double.valueOf(jTValor2.getText());
            jLResultado.setText("Multiplicação " + calcule(new Multiplicacao(), pvalor1, pvalor2));
            jTValor1.setText("");
            jTValor2.setText("");
            jTValor1.requestFocus();
        }
    }//GEN-LAST:event_jBMultiplicacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDivisao;
    private javax.swing.JButton jBMedia;
    private javax.swing.JButton jBMultiplicacao;
    private javax.swing.JButton jBSoma;
    private javax.swing.JButton jBSubtracao;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTValor1;
    private javax.swing.JTextField jTValor2;
    // End of variables declaration//GEN-END:variables
}
